# -*- coding: utf-8 -*-
"""aio_keyword_checker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnGsyOLobInRlK_6YLp8kq8Bna_D8mil
"""

!pip install requests
!pip install -q httpx orjson tqdm pandas

import requests
import asyncio, json, random, time, math
import httpx, orjson, pandas as pd
from tqdm.auto import tqdm
from typing import List, Dict, Any, Iterable, Optional

"""# Setting up API"""

sheet_url = "https://docs.google.com/spreadsheets/d/1-8bOvaGnwuC1XnMaXwBMuAsEb9ToliI0oyDDpU8OMWY/edit?gid=0#gid=0"
csv_url = sheet_url.replace('/edit?gid=', '/export?format=csv&gid=')

try:
  df_sheet = pd.read_csv(csv_url)
  # print("Data successfully loaded from Google Sheet:")
  # display(df_sheet.head())
except Exception as e:
  print(f"Error loading data from Google Sheet: {e}")

sheet_df = pd.DataFrame(df_sheet)
sheet_df = sheet_df.dropna(subset=['Từ khóa'])
sheet_df.head()
keywords = sheet_df['Từ khóa'].tolist()


print(keywords[:10])
print(len(keywords))

import json, requests, pandas as pd
from tqdm.auto import tqdm
from concurrent.futures import ThreadPoolExecutor

url = "https://api.dataforseo.com/v3/serp/google/organic/live/advanced"
headers = {
    'Authorization': 'Basic YWl0ZWFtQHNlb25nb24uY29tOjcyMmU2MzI4OGU4NzRmMzk=',
    'Content-Type': 'application/json'
}

# Change the country code and language here as appropriate
def dataforseo(keyword):
    payload = json.dumps([{
        "keyword": keyword,
        "location_code": 2704,
        "language_code": "vi",
        "depth": 10,
        "group_organic_results": True,
        "load_async_ai_overview": True
    }])
    response = requests.request("POST", url, headers=headers, data=payload)
    return response.text

def process_keyword(keyword):
    data = dataforseo(keyword)
    data = json.loads(data)
    # EXACTLY what you did before:
    return data['tasks'][0]['result']

MAX_WORKERS = 32  # try 32–64 for IO-bound; lower if you hit rate limits

api_data = []
with ThreadPoolExecutor(max_workers=MAX_WORKERS) as ex:
    for result in tqdm(ex.map(process_keyword, keywords),
                       total=len(keywords),
                       desc="Fetching data for keywords (parallel)"):
        api_data.append(result)

# Same saving logic you had
api_dataframe = pd.DataFrame(api_data)
file_name = 'result.json'
api_dataframe.to_json(file_name)

# Colab download
try:
    from google.colab import files
    files.download(file_name)
except Exception:
    pass