name = "directus-blog"
main = ".vercel/output/static/_worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".vercel/output/static"

[build]
command = "npx @cloudflare/next-on-pages@1"

[vars]
NEXT_PUBLIC_DIRECTUS_API_ENDPOINT = "https://directus-production-b969.up.railway.app"